name: Future Work Widget Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - future-work-action # TODO: change back to main before merging
    paths:
      - 'docs/future-work/**'
      - 'docs/snippets/**'
      - 'tools/future_work_widget/**'
      - '.github/workflows/future_work_widget_deploy.yml'
  pull_request: # REMOVE BEFORE MERGEING
    branches:
      - future-work-action 
    paths:
      - 'docs/future-work/**'
      - 'docs/snippets/**'
      - 'tools/future_work_widget/**'
      - '.github/workflows/future_work_widget_deploy.yml'

jobs:
  future_work_widget_deploy:
    name: future-work-widget-deploy
    runs-on: ubuntu-latest
    # if: ${{ github.repository_owner == 'thousandbrainsproject' }}
    steps:
      - name: Checkout tbp.monty
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          path: tbp.monty
      - name: Set up ~/tbp
        run: |
          mkdir -p ~/tbp
          ln -s $GITHUB_WORKSPACE/tbp.monty ~/tbp/tbp.monty
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install miniconda
        run: |
          if [ ! -d ~/miniconda ]
          then
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -b -p ~/miniconda
            rm ~/miniconda.sh
          fi
          export PATH="$HOME/miniconda/bin:$PATH"
          conda --version
      - name: Create conda environment
        working-directory: tbp.monty
        run: |
          export PATH="$HOME/miniconda/bin:$PATH"
          (conda env list | grep tbp.monty) && conda remove --name tbp.monty --all --yes || true
          conda env create
          source activate tbp.monty
          pip install -e .[dev,github_readme_sync_tool,future_work_widget_tool]
      - name: Build future work widget
        working-directory: tbp.monty
        run: |
          export PATH="$HOME/miniconda/bin:$PATH"
          source activate tbp.monty
          python -m tools.github_readme_sync.cli generate-index docs "${{ runner.temp }}/index.json"
          mkdir -p "${{ runner.temp }}/future-work-widget"
          cp -r tools/future_work_widget/app/* "${{ runner.temp }}/future-work-widget/"
          python -m tools.future_work_widget.cli "${{ runner.temp }}/index.json" "${{ runner.temp }}/future-work-widget"
          ls -lR "${{ runner.temp }}"/future-work-widget
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.FUTURE_WORK_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FUTURE_WORK_SECRET_ACCESS_KEY }}
          aws-region: ${{ 'us-east-1' }}
      - name: Upload future work widget to S3
        run: |
          aws s3 sync "${{ runner.temp }}/future-work-widget/" s3://${{ secrets.FUTURE_WORK_S3_BUCKET_NAME }}/future-work-widget/ --delete
